In [1]:
import pandas as pd
import numpy as np

In [18]:
data = pd.read_excel("TransmissionModel.xlsx",sheet_name = "cap__0")

In [19]:
data['Unnamed: 0'] = data['Unnamed: 0'].ffill()
data

,Unnamed: 0,Unnamed: 1,cluster_0,cluster_1,cluster_2,cluster_3,cluster_4,cluster_5,cluster_6,cluster_7
0,AC cables,cluster_0,NaN,7.000000,11.000000,NaN,18.000000,4.000000,NaN,2.500000
1,AC cables,cluster_1,7.000000,NaN,10.000000,NaN,NaN,3.000000,6.000000,NaN
2,AC cables,cluster_2,11.000000,10.000000,NaN,NaN,NaN,NaN,NaN,3.000000
3,AC cables,cluster_3,NaN,NaN,NaN,NaN,NaN,12.000000,2.400000,NaN
4,AC cables,cluster_4,18.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN
5,AC cables,cluster_5,4.000000,3.000000,NaN,12.000000,4.000000,NaN,NaN,NaN
6,AC cables,cluster_6,NaN,6.000000,NaN,2.400000,NaN,NaN,NaN,NaN
7,AC cables,cluster_7,2.500000,NaN,3.000000,NaN,NaN,NaN,NaN,NaN
8,DC cables,cluster_0,NaN,NaN,2.000000,NaN,NaN,NaN,4.000000,NaN
9,DC cables,cluster_2,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,DC cables,cluster_4,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN
11,DC cables,cluster_5,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN
12,DC cables,cluster_6,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Pipelines (biogas),cluster_0,NaN,0.000000,0.837743,NaN,0.280109,0.000000,NaN,0.000000
14,Pipelines (biogas),cluster_1,0.000000,NaN,0.000000,0.000000,NaN,0.000000,0.347960,NaN
15,Pipelines (biogas),cluster_2,0.837743,0.000000,NaN,NaN,NaN,NaN,NaN,0.139259
16,Pipelines (biogas),cluster_3,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,NaN
17,Pipelines (biogas),cluster_4,0.280109,NaN,NaN,NaN,NaN,0.461621,NaN,NaN
18,Pipelines (biogas),cluster_5,0.000000,0.000000,NaN,0.000000,0.461621,NaN,NaN,NaN
19,Pipelines (biogas),cluster_6,NaN,0.347960,NaN,0.000000,NaN,NaN,NaN,NaN
20,Pipelines (biogas),cluster_7,0.000000,NaN,0.139259,NaN,NaN,NaN,NaN,NaN
21,Pipelines (hydrogen),cluster_0,NaN,1.647697,1.312748,NaN,1.150487,0.000000,NaN,0.000000
22,Pipelines (hydrogen),cluster_1,1.647697,NaN,0.008120,0.000000,NaN,0.000000,3.237727,NaN
23,Pipelines (hydrogen),cluster_2,1.312748,0.008120,NaN,NaN,NaN,NaN,NaN,0.165882
24,Pipelines (hydrogen),cluster_3,NaN,0.000000,NaN,NaN,NaN,0.000000,0.600928,NaN
25,Pipelines (hydrogen),cluster_4,1.150487,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
26,Pipelines (hydrogen),cluster_5,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN
27,Pipelines (hydrogen),cluster_6,NaN,3.237727,NaN,0.600928,NaN,NaN,NaN,NaN
28,Pipelines (hydrogen),cluster_7,0.000000,NaN,0.165882,NaN,NaN,NaN,NaN,NaN

In [20]:
locations = [
    "cluster_0",
    "cluster_1",
    "cluster_2",
    "cluster_3",
    "cluster_4",
    "cluster_5",
    "cluster_6",
    "cluster_7",
]

In [21]:
# data.set_index(['Unnamed: 0','Unnamed: 1'],inplace=True)
multi_index = [(data.loc[i,"Unnamed: 0"],data.loc[i,"Unnamed: 1"],column) for i in data.index 
                                       for column in locations]

In [22]:
multi_index

[('AC cables', 'cluster_0', 'cluster_0'),
 ('AC cables', 'cluster_0', 'cluster_1'),
 ('AC cables', 'cluster_0', 'cluster_2'),
 ('AC cables', 'cluster_0', 'cluster_3'),
 ('AC cables', 'cluster_0', 'cluster_4'),
 ('AC cables', 'cluster_0', 'cluster_5'),
 ('AC cables', 'cluster_0', 'cluster_6'),
 ('AC cables', 'cluster_0', 'cluster_7'),
 ('AC cables', 'cluster_1', 'cluster_0'),
 ('AC cables', 'cluster_1', 'cluster_1'),
 ('AC cables', 'cluster_1', 'cluster_2'),
 ('AC cables', 'cluster_1', 'cluster_3'),
 ('AC cables', 'cluster_1', 'cluster_4'),
 ('AC cables', 'cluster_1', 'cluster_5'),
 ('AC cables', 'cluster_1', 'cluster_6'),
 ('AC cables', 'cluster_1', 'cluster_7'),
 ('AC cables', 'cluster_2', 'cluster_0'),
 ('AC cables', 'cluster_2', 'cluster_1'),
 ('AC cables', 'cluster_2', 'cluster_2'),
 ('AC cables', 'cluster_2', 'cluster_3'),
 ('AC cables', 'cluster_2', 'cluster_4'),
 ('AC cables', 'cluster_2', 'cluster_5'),
 ('AC cables', 'cluster_2', 'cluster_6'),
 ('AC cables', 'cluster_2', 'cluster_7'),
 ('AC cables', 'cluster_3', 'cluster_0'),
 ('AC cables', 'cluster_3', 'cluster_1'),
 ('AC cables', 'cluster_3', 'cluster_2'),
 ('AC cables', 'cluster_3', 'cluster_3'),
 ('AC cables', 'cluster_3', 'cluster_4'),
 ('AC cables', 'cluster_3', 'cluster_5'),
 ('AC cables', 'cluster_3', 'cluster_6'),
 ('AC cables', 'cluster_3', 'cluster_7'),
 ('AC cables', 'cluster_4', 'cluster_0'),
 ('AC cables', 'cluster_4', 'cluster_1'),
 ('AC cables', 'cluster_4', 'cluster_2'),
 ('AC cables', 'cluster_4', 'cluster_3'),
 ('AC cables', 'cluster_4', 'cluster_4'),
 ('AC cables', 'cluster_4', 'cluster_5'),
 ('AC cables', 'cluster_4', 'cluster_6'),
 ('AC cables', 'cluster_4', 'cluster_7'),
 ('AC cables', 'cluster_5', 'cluster_0'),
 ('AC cables', 'cluster_5', 'cluster_1'),
 ('AC cables', 'cluster_5', 'cluster_2'),
 ('AC cables', 'cluster_5', 'cluster_3'),
 ('AC cables', 'cluster_5', 'cluster_4'),
 ('AC cables', 'cluster_5', 'cluster_5'),
 ('AC cables', 'cluster_5', 'cluster_6'),
 ('AC cables', 'cluster_5', 'cluster_7'),
 ('AC cables', 'cluster_6', 'cluster_0'),
 ('AC cables', 'cluster_6', 'cluster_1'),
 ('AC cables', 'cluster_6', 'cluster_2'),
 ('AC cables', 'cluster_6', 'cluster_3'),
 ('AC cables', 'cluster_6', 'cluster_4'),
 ('AC cables', 'cluster_6', 'cluster_5'),
 ('AC cables', 'cluster_6', 'cluster_6'),
 ('AC cables', 'cluster_6', 'cluster_7'),
 ('AC cables', 'cluster_7', 'cluster_0'),
 ('AC cables', 'cluster_7', 'cluster_1'),
 ('AC cables', 'cluster_7', 'cluster_2'),
 ('AC cables', 'cluster_7', 'cluster_3'),
 ('AC cables', 'cluster_7', 'cluster_4'),
 ('AC cables', 'cluster_7', 'cluster_5'),
 ('AC cables', 'cluster_7', 'cluster_6'),
 ('AC cables', 'cluster_7', 'cluster_7'),
 ('DC cables', 'cluster_0', 'cluster_0'),
 ('DC cables', 'cluster_0', 'cluster_1'),
 ('DC cables', 'cluster_0', 'cluster_2'),
 ('DC cables', 'cluster_0', 'cluster_3'),
 ('DC cables', 'cluster_0', 'cluster_4'),
 ('DC cables', 'cluster_0', 'cluster_5'),
 ('DC cables', 'cluster_0', 'cluster_6'),
 ('DC cables', 'cluster_0', 'cluster_7'),
 ('DC cables', 'cluster_2', 'cluster_0'),
 ('DC cables', 'cluster_2', 'cluster_1'),
 ('DC cables', 'cluster_2', 'cluster_2'),
 ('DC cables', 'cluster_2', 'cluster_3'),
 ('DC cables', 'cluster_2', 'cluster_4'),
 ('DC cables', 'cluster_2', 'cluster_5'),
 ('DC cables', 'cluster_2', 'cluster_6'),
 ('DC cables', 'cluster_2', 'cluster_7'),
 ('DC cables', 'cluster_4', 'cluster_0'),
 ('DC cables', 'cluster_4', 'cluster_1'),
 ('DC cables', 'cluster_4', 'cluster_2'),
 ('DC cables', 'cluster_4', 'cluster_3'),
 ('DC cables', 'cluster_4', 'cluster_4'),
 ('DC cables', 'cluster_4', 'cluster_5'),
 ('DC cables', 'cluster_4', 'cluster_6'),
 ('DC cables', 'cluster_4', 'cluster_7'),
 ('DC cables', 'cluster_5', 'cluster_0'),
 ('DC cables', 'cluster_5', 'cluster_1'),
 ('DC cables', 'cluster_5', 'cluster_2'),
 ('DC cables', 'cluster_5', 'cluster_3'),
 ('DC cables', 'cluster_5', 'cluster_4'),
 ('DC cables', 'cluster_5', 'cluster_5'),
 ('DC cables', 'cluster_5', 'cluster_6'),
 ('DC cables', 'cluster_5', 'cluster_7'),
 ('DC cables', 'cluster_6', 'cluster_0'),
 ('DC cables', 'cluster_6', 'cluster_1'),
 ('DC cables', 'cluster_6', 'cluster_2'),
 ('DC cables', 'cluster_6', 'cluster_3'),
 ('DC cables', 'cluster_6', 'cluster_4'),
 ('DC cables', 'cluster_6', 'cluster_5'),
 ('DC cables', 'cluster_6', 'cluster_6'),
 ('DC cables', 'cluster_6', 'cluster_7'),
 ('Pipelines (biogas)', 'cluster_0', 'cluster_0'),
 ('Pipelines (biogas)', 'cluster_0', 'cluster_1'),
 ('Pipelines (biogas)', 'cluster_0', 'cluster_2'),
 ('Pipelines (biogas)', 'cluster_0', 'cluster_3'),
 ('Pipelines (biogas)', 'cluster_0', 'cluster_4'),
 ('Pipelines (biogas)', 'cluster_0', 'cluster_5'),
 ('Pipelines (biogas)', 'cluster_0', 'cluster_6'),
 ('Pipelines (biogas)', 'cluster_0', 'cluster_7'),
 ('Pipelines (biogas)', 'cluster_1', 'cluster_0'),
 ('Pipelines (biogas)', 'cluster_1', 'cluster_1'),
 ('Pipelines (biogas)', 'cluster_1', 'cluster_2'),
 ('Pipelines (biogas)', 'cluster_1', 'cluster_3'),
 ('Pipelines (biogas)', 'cluster_1', 'cluster_4'),
 ('Pipelines (biogas)', 'cluster_1', 'cluster_5'),
 ('Pipelines (biogas)', 'cluster_1', 'cluster_6'),
 ('Pipelines (biogas)', 'cluster_1', 'cluster_7'),
 ('Pipelines (biogas)', 'cluster_2', 'cluster_0'),
 ('Pipelines (biogas)', 'cluster_2', 'cluster_1'),
 ('Pipelines (biogas)', 'cluster_2', 'cluster_2'),
 ('Pipelines (biogas)', 'cluster_2', 'cluster_3'),
 ('Pipelines (biogas)', 'cluster_2', 'cluster_4'),
 ('Pipelines (biogas)', 'cluster_2', 'cluster_5'),
 ('Pipelines (biogas)', 'cluster_2', 'cluster_6'),
 ('Pipelines (biogas)', 'cluster_2', 'cluster_7'),
 ('Pipelines (biogas)', 'cluster_3', 'cluster_0'),
 ('Pipelines (biogas)', 'cluster_3', 'cluster_1'),
 ('Pipelines (biogas)', 'cluster_3', 'cluster_2'),
 ('Pipelines (biogas)', 'cluster_3', 'cluster_3'),
 ('Pipelines (biogas)', 'cluster_3', 'cluster_4'),
 ('Pipelines (biogas)', 'cluster_3', 'cluster_5'),
 ('Pipelines (biogas)', 'cluster_3', 'cluster_6'),
 ('Pipelines (biogas)', 'cluster_3', 'cluster_7'),
 ('Pipelines (biogas)', 'cluster_4', 'cluster_0'),
 ('Pipelines (biogas)', 'cluster_4', 'cluster_1'),
 ('Pipelines (biogas)', 'cluster_4', 'cluster_2'),
 ('Pipelines (biogas)', 'cluster_4', 'cluster_3'),
 ('Pipelines (biogas)', 'cluster_4', 'cluster_4'),
 ('Pipelines (biogas)', 'cluster_4', 'cluster_5'),
 ('Pipelines (biogas)', 'cluster_4', 'cluster_6'),
 ('Pipelines (biogas)', 'cluster_4', 'cluster_7'),
 ('Pipelines (biogas)', 'cluster_5', 'cluster_0'),
 ('Pipelines (biogas)', 'cluster_5', 'cluster_1'),
 ('Pipelines (biogas)', 'cluster_5', 'cluster_2'),
 ('Pipelines (biogas)', 'cluster_5', 'cluster_3'),
 ('Pipelines (biogas)', 'cluster_5', 'cluster_4'),
 ('Pipelines (biogas)', 'cluster_5', 'cluster_5'),
 ('Pipelines (biogas)', 'cluster_5', 'cluster_6'),
 ('Pipelines (biogas)', 'cluster_5', 'cluster_7'),
 ('Pipelines (biogas)', 'cluster_6', 'cluster_0'),
 ('Pipelines (biogas)', 'cluster_6', 'cluster_1'),
 ('Pipelines (biogas)', 'cluster_6', 'cluster_2'),
 ('Pipelines (biogas)', 'cluster_6', 'cluster_3'),
 ('Pipelines (biogas)', 'cluster_6', 'cluster_4'),
 ('Pipelines (biogas)', 'cluster_6', 'cluster_5'),
 ('Pipelines (biogas)', 'cluster_6', 'cluster_6'),
 ('Pipelines (biogas)', 'cluster_6', 'cluster_7'),
 ('Pipelines (biogas)', 'cluster_7', 'cluster_0'),
 ('Pipelines (biogas)', 'cluster_7', 'cluster_1'),
 ('Pipelines (biogas)', 'cluster_7', 'cluster_2'),
 ('Pipelines (biogas)', 'cluster_7', 'cluster_3'),
 ('Pipelines (biogas)', 'cluster_7', 'cluster_4'),
 ('Pipelines (biogas)', 'cluster_7', 'cluster_5'),
 ('Pipelines (biogas)', 'cluster_7', 'cluster_6'),
 ('Pipelines (biogas)', 'cluster_7', 'cluster_7'),
 ('Pipelines (hydrogen)', 'cluster_0', 'cluster_0'),
 ('Pipelines (hydrogen)', 'cluster_0', 'cluster_1'),
 ('Pipelines (hydrogen)', 'cluster_0', 'cluster_2'),
 ('Pipelines (hydrogen)', 'cluster_0', 'cluster_3'),
 ('Pipelines (hydrogen)', 'cluster_0', 'cluster_4'),
 ('Pipelines (hydrogen)', 'cluster_0', 'cluster_5'),
 ('Pipelines (hydrogen)', 'cluster_0', 'cluster_6'),
 ('Pipelines (hydrogen)', 'cluster_0', 'cluster_7'),
 ('Pipelines (hydrogen)', 'cluster_1', 'cluster_0'),
 ('Pipelines (hydrogen)', 'cluster_1', 'cluster_1'),
 ('Pipelines (hydrogen)', 'cluster_1', 'cluster_2'),
 ('Pipelines (hydrogen)', 'cluster_1', 'cluster_3'),
 ('Pipelines (hydrogen)', 'cluster_1', 'cluster_4'),
 ('Pipelines (hydrogen)', 'cluster_1', 'cluster_5'),
 ('Pipelines (hydrogen)', 'cluster_1', 'cluster_6'),
 ('Pipelines (hydrogen)', 'cluster_1', 'cluster_7'),
 ('Pipelines (hydrogen)', 'cluster_2', 'cluster_0'),
 ('Pipelines (hydrogen)', 'cluster_2', 'cluster_1'),
 ('Pipelines (hydrogen)', 'cluster_2', 'cluster_2'),
 ('Pipelines (hydrogen)', 'cluster_2', 'cluster_3'),
 ('Pipelines (hydrogen)', 'cluster_2', 'cluster_4'),
 ('Pipelines (hydrogen)', 'cluster_2', 'cluster_5'),
 ('Pipelines (hydrogen)', 'cluster_2', 'cluster_6'),
 ('Pipelines (hydrogen)', 'cluster_2', 'cluster_7'),
 ('Pipelines (hydrogen)', 'cluster_3', 'cluster_0'),
 ('Pipelines (hydrogen)', 'cluster_3', 'cluster_1'),
 ('Pipelines (hydrogen)', 'cluster_3', 'cluster_2'),
 ('Pipelines (hydrogen)', 'cluster_3', 'cluster_3'),
 ('Pipelines (hydrogen)', 'cluster_3', 'cluster_4'),
 ('Pipelines (hydrogen)', 'cluster_3', 'cluster_5'),
 ('Pipelines (hydrogen)', 'cluster_3', 'cluster_6'),
 ('Pipelines (hydrogen)', 'cluster_3', 'cluster_7'),
 ('Pipelines (hydrogen)', 'cluster_4', 'cluster_0'),
 ('Pipelines (hydrogen)', 'cluster_4', 'cluster_1'),
 ('Pipelines (hydrogen)', 'cluster_4', 'cluster_2'),
 ('Pipelines (hydrogen)', 'cluster_4', 'cluster_3'),
 ('Pipelines (hydrogen)', 'cluster_4', 'cluster_4'),
 ('Pipelines (hydrogen)', 'cluster_4', 'cluster_5'),
 ('Pipelines (hydrogen)', 'cluster_4', 'cluster_6'),
 ('Pipelines (hydrogen)', 'cluster_4', 'cluster_7'),
 ('Pipelines (hydrogen)', 'cluster_5', 'cluster_0'),
 ('Pipelines (hydrogen)', 'cluster_5', 'cluster_1'),
 ('Pipelines (hydrogen)', 'cluster_5', 'cluster_2'),
 ('Pipelines (hydrogen)', 'cluster_5', 'cluster_3'),
 ('Pipelines (hydrogen)', 'cluster_5', 'cluster_4'),
 ('Pipelines (hydrogen)', 'cluster_5', 'cluster_5'),
 ('Pipelines (hydrogen)', 'cluster_5', 'cluster_6'),
 ('Pipelines (hydrogen)', 'cluster_5', 'cluster_7'),
 ('Pipelines (hydrogen)', 'cluster_6', 'cluster_0'),
 ('Pipelines (hydrogen)', 'cluster_6', 'cluster_1'),
 ('Pipelines (hydrogen)', 'cluster_6', 'cluster_2'),
 ('Pipelines (hydrogen)', 'cluster_6', 'cluster_3'),
 ('Pipelines (hydrogen)', 'cluster_6', 'cluster_4'),
 ('Pipelines (hydrogen)', 'cluster_6', 'cluster_5'),
 ('Pipelines (hydrogen)', 'cluster_6', 'cluster_6'),
 ('Pipelines (hydrogen)', 'cluster_6', 'cluster_7'),
 ('Pipelines (hydrogen)', 'cluster_7', 'cluster_0'),
 ('Pipelines (hydrogen)', 'cluster_7', 'cluster_1'),
 ('Pipelines (hydrogen)', 'cluster_7', 'cluster_2'),
 ('Pipelines (hydrogen)', 'cluster_7', 'cluster_3'),
 ('Pipelines (hydrogen)', 'cluster_7', 'cluster_4'),
 ('Pipelines (hydrogen)', 'cluster_7', 'cluster_5'),
 ('Pipelines (hydrogen)', 'cluster_7', 'cluster_6'),
 ('Pipelines (hydrogen)', 'cluster_7', 'cluster_7')]

In [23]:
multi = pd.MultiIndex.from_tuples(multi_index)
df = pd.DataFrame(data = 0.0, index = [i for i in range(10)],columns = multi)
df

  AC cables                                                              \
  cluster_0
  cluster_0 cluster_1 cluster_2 cluster_3 cluster_4 cluster_5 cluster_6
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0
3       0.0       0.0       0.0       0.0       0.0       0.0       0.0
4       0.0       0.0       0.0       0.0       0.0       0.0       0.0
5       0.0       0.0       0.0       0.0       0.0       0.0       0.0
6       0.0       0.0       0.0       0.0       0.0       0.0       0.0
7       0.0       0.0       0.0       0.0       0.0       0.0       0.0
8       0.0       0.0       0.0       0.0       0.0       0.0       0.0
9       0.0       0.0       0.0       0.0       0.0       0.0       0.0

                                 ... Pipelines (hydrogen)                      \
            cluster_1            ...            cluster_6           cluster_7
  cluster_7 cluster_0 cluster_1  ...            cluster_6 cluster_7 cluster_0
0       0.0       0.0       0.0  ...                  0.0       0.0       0.0
1       0.0       0.0       0.0  ...                  0.0       0.0       0.0
2       0.0       0.0       0.0  ...                  0.0       0.0       0.0
3       0.0       0.0       0.0  ...                  0.0       0.0       0.0
4       0.0       0.0       0.0  ...                  0.0       0.0       0.0
5       0.0       0.0       0.0  ...                  0.0       0.0       0.0
6       0.0       0.0       0.0  ...                  0.0       0.0       0.0
7       0.0       0.0       0.0  ...                  0.0       0.0       0.0
8       0.0       0.0       0.0  ...                  0.0       0.0       0.0
9       0.0       0.0       0.0  ...                  0.0       0.0       0.0



  cluster_1 cluster_2 cluster_3 cluster_4 cluster_5 cluster_6 cluster_7
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0
3       0.0       0.0       0.0       0.0       0.0       0.0       0.0
4       0.0       0.0       0.0       0.0       0.0       0.0       0.0
5       0.0       0.0       0.0       0.0       0.0       0.0       0.0
6       0.0       0.0       0.0       0.0       0.0       0.0       0.0
7       0.0       0.0       0.0       0.0       0.0       0.0       0.0
8       0.0       0.0       0.0       0.0       0.0       0.0       0.0
9       0.0       0.0       0.0       0.0       0.0       0.0       0.0

[10 rows x 232 columns]

In [25]:
df.loc[2,multi_index[1]]

0.0

In [67]:
for i, (component, values) in enumerate(multi_index):
    for j, value in enumerate(values):
        print(i, component, value)

0 Wind (offshore) cluster_1
0 Wind (offshore) cluster_2
0 Wind (offshore) cluster_3
0 Wind (offshore) cluster_6
1 Biogas purchase cluster_0
1 Biogas purchase cluster_1
1 Biogas purchase cluster_2
1 Biogas purchase cluster_3
1 Biogas purchase cluster_4
1 Biogas purchase cluster_5
1 Biogas purchase cluster_6
1 Biogas purchase cluster_7
2 Wind (onshore) cluster_0
2 Wind (onshore) cluster_1
2 Wind (onshore) cluster_2
2 Wind (onshore) cluster_3
2 Wind (onshore) cluster_4
2 Wind (onshore) cluster_5
2 Wind (onshore) cluster_6
2 Wind (onshore) cluster_7
3 Hydrogen demand cluster_0
3 Hydrogen demand cluster_1
3 Hydrogen demand cluster_2
3 Hydrogen demand cluster_3
3 Hydrogen demand cluster_4
3 Hydrogen demand cluster_5
3 Hydrogen demand cluster_6
3 Hydrogen demand cluster_7
4 Existing run-of-river plants cluster_0
4 Existing run-of-river plants cluster_1
4 Existing run-of-river plants cluster_2
4 Existing run-of-river plants cluster_3
4 Existing run-of-river plants cluster_4
4 Existing run-of-river plants cluster_7
5 CO2 to enviroment cluster_0
5 CO2 to enviroment cluster_1
5 CO2 to enviroment cluster_2
5 CO2 to enviroment cluster_3
5 CO2 to enviroment cluster_4
5 CO2 to enviroment cluster_5
5 CO2 to enviroment cluster_6
5 CO2 to enviroment cluster_7
6 Electricity demand cluster_0
6 Electricity demand cluster_1
6 Electricity demand cluster_2
6 Electricity demand cluster_3
6 Electricity demand cluster_4
6 Electricity demand cluster_5
6 Electricity demand cluster_6
6 Electricity demand cluster_7
7 Natural gas purchase cluster_0
7 Natural gas purchase cluster_1
7 Natural gas purchase cluster_2
7 Natural gas purchase cluster_3
7 Natural gas purchase cluster_4
7 Natural gas purchase cluster_5
7 Natural gas purchase cluster_6
7 Natural gas purchase cluster_7
8 PV cluster_0
8 PV cluster_1
8 PV cluster_2
8 PV cluster_3
8 PV cluster_4
8 PV cluster_5
8 PV cluster_6
8 PV cluster_7