In [1]:
from IPython.display import Image
Image("images\strukturExample.png");

# Workflow for the EnergyLand energy system

In this application of the FINE framework, a 1-node energy system is modeled and optimized.

The workflow is structures as follows:
1. Required packages are imported and the input data path is set
2. An energy system model instance is created
3. Commodity sources are added to the energy system model
4. Commodity conversion components are added to the energy system model
5. Commodity storages are added to the energy system model
6. Commodity sinks are added to the energy system model
7. The energy system model is optimized
8. Selected optimization results are presented

![Structure of EnergyLand](images\strukturExample.png)

# 1. Import packages

The FINE framework is imported which provides the required classes and functions for modeling the energy system.
The working directory and the underlying excelfile which provides some of the input data is imported.

In [2]:
import FINE as fn
from getData import getData
import pandas as pd
import os
cwd = os.getcwd()
data = getData()

# 2. Set up energy system model instance

The structure of the energy system model is given by the considered locations, in this case we consider only one location (EnergyLand), commodities, the number of time steps as well as the hours per time step.

The commodities are specified by a unit, which can be given as an energy or mass unit per hour.

In [3]:
locations = {'EnergyLand'}
commodityUnitDict = {'electricity': r'GW$_{el}$', 'hydrogen': r'GW$_{H_{2},LHV}$', 
                     'nGas':r'GW$_{CH4}$', 'coal':r'GW$_{coal}$', 'PHeat': r'GW$_{Pheat}$',
                     'LTHeat':r'GW$_{LTHeat}$', 'CO2':r'kt$_{CO_{2}}$/h', 'pTransport': 'Mio pkm/h',
                     'fTransport': 'Mio tkm/h', 'crudeOil': r'GW$_{Oil}$', 'wood': r'GW$_{wood}$', 
                     'biowaste': r'GW$_{biowaste}$', 'bioslurry': r'GW$_{bioslurry}$',
                     'diesel': r'GW$_{diesel}$', 'biogas': r'GW$_{CH4}$', 'nGasImp': r'GW$_{CH4}$'}
commodities = {'electricity', 'hydrogen', 'nGas', 'coal', 'PHeat', 'LTHeat', 'CO2', 'pTransport', 
               'fTransport', 'crudeOil', 'wood', 'biowaste', 'bioslurry', 'diesel', 'nGasImp', 'biogas'}
numberOfTimeSteps=8760
hoursPerTimeStep=1

In [4]:
esM = fn.EnergySystemModel(locations=locations, commodities=commodities, numberOfTimeSteps=8760,
                           commodityUnitsDict=commodityUnitDict,
                           hoursPerTimeStep=1, costUnit='1e6 Euro', lengthUnit='km', verboseLogLevel=0)

# 3. Sources

Source components transfer a commodity from outside the system boundary of EnergyLand into the system.

## 3.1 Electricity sources

### Wind turbines

#### Onshore Wind Turbines

In [5]:
esM.add(fn.Source(esM=esM, name='Wind_Onshore', commodity='electricity', hasCapacityVariable=True,
                  operationRateMax=data['Wind_onshore, operationRateMax'],
                  capacityMax=data['Wind_onshore, capacityMax'],
                  investPerCapacity=1250, opexPerCapacity=1250*0.02, interestRate=0.08,
                  economicLifetime=20))

#### Offshore Wind Turbines

In [6]:
esM.add(fn.Source(esM=esM, name='Wind_Offshore', commodity='electricity', hasCapacityVariable=True,
                  operationRateMax=data['Wind_offshore, operationRateMax'],
                  capacityMax=data['Wind_offshore, capacityMax'],
                  investPerCapacity=2530, opexPerCapacity=2530*0.045, interestRate=0.08,
                  economicLifetime=20))

### Photovoltaic

In [7]:
esM.add(fn.Source(esM=esM, name='PV', commodity='electricity', hasCapacityVariable=True,
                  operationRateMax=data['PV, operationRateMax'],
                  capacityMax=data['PV, capacityMax'],
                  investPerCapacity=800, opexPerCapacity=800*0.019, interestRate=0.08,
                  economicLifetime=20))

### Electricity import

In [8]:
esM.add(fn.Source(esM=esM, name='el_Import', commodity='electricity', hasCapacityVariable=False,
                  operationRateMax=data['el_Import, operationRateMax']))

## 3.2 Hydrogen source

In [9]:
esM.add(fn.Source(esM=esM, name='H2_Import', commodity='hydrogen', hasCapacityVariable=False,
                  operationRateMax=data['H2_Import, operationRateMax'],
                  commodityCost=0.132))

## 3.3 Coal source

In [10]:
esM.add(fn.Source(esM=esM, name='CoalSource', commodity='coal', hasCapacityVariable=False,
                  commodityCost=0.021))

## 3.4 Crude Oil source

In [11]:
esM.add(fn.Source(esM=esM, name='CrudeOilSource', commodity='crudeOil', hasCapacityVariable=False,
                  commodityCost=0.036))

## 3.5 Natural gas source

In [12]:
esM.add(fn.Source(esM=esM, name='nGasSource', commodity='nGasImp', hasCapacityVariable=False,
                  commodityCost=0.0256))

## 3.6 Biomass sources

#### Wood Source

In [13]:
esM.add(fn.Source(esM=esM, name='WoodSource', commodity='wood', hasCapacityVariable=True,
                  capacityMax=data['wood_source, capacityMax'],
                  commodityCost=0.028))

#### Biowaste Source

In [14]:
esM.add(fn.Source(esM=esM, name='BiowasteSource', commodity='biowaste', hasCapacityVariable=True,
                  capacityMax=data['biowaste_source, capacityMax'],
                  commodityCost=0.07))

#### Bioslurry Source

In [15]:
esM.add(fn.Source(esM=esM, name='BioslurrySource', commodity='bioslurry', hasCapacityVariable=True,
                  capacityMax=data['bioslurry_source, capacityMax'],
                  commodityCost=0.07))

# 4. Conversion components

These are the components which can transfer one commodity into another one.

## 4.1 Biomas to biogas

### Bioslurry to Biogas

In [16]:
esM.add(fn.Conversion(esM=esM, name='bioslurry-biogas', physicalUnit= r'GW$_{CH4}$',
                      commodityConversionFactors={'bioslurry':-1, 'biogas':1},
                      hasCapacityVariable=False))

### Biowaste to Biogas

In [17]:
esM.add(fn.Conversion(esM=esM, name='biowaste-biogas', physicalUnit= r'GW$_{CH4}$',
                      commodityConversionFactors={'biowaste':-1, 'biogas':1},
                      hasCapacityVariable=False))

## 4.2 Methane Slip (Virtual conversion)

In [18]:
methaneSlip=0.1
esM.add(fn.Conversion(esM=esM, name='CH4Slip', physicalUnit= r'GW$_{CH4}$',
                      commodityConversionFactors={'nGasImp':-1, 'nGas':1, 'CO2':methaneSlip*2.014},
                      hasCapacityVariable=False))

## 4.3 Biogas to Methane (Virtual conversion)

In [19]:
esM.add(fn.Conversion(esM=esM, name='biogas-nGas', physicalUnit= r'GW$_{CH4}$',
                      commodityConversionFactors={'biogas':-1, 'nGas':1, 'CO2':-0.2014},
                      hasCapacityVariable=True, opexPerOperation=0.0003,
                      investPerCapacity=343, opexPerCapacity=343*0.025, interestRate=0.08,
                      economicLifetime=15))

## 4.4 Transport

### Batterie Electric Vehicle

#### BEV Car

In [20]:
esM.add(fn.Conversion(esM=esM, name='BEV_PCar', physicalUnit= r'Mio pkm/h',
                      commodityConversionFactors={'electricity':-1/7.676226, 'pTransport':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=15694, opexPerCapacity=15694*0.009, interestRate=0.08,
                      economicLifetime=12))

#### BEV Truck

In [21]:
esM.add(fn.Conversion(esM=esM, name='BEV_Truck', physicalUnit= r'Mio tkm/h',
                      commodityConversionFactors={'electricity':-1/11.401, 'fTransport':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=4304, opexPerCapacity=4304*0.009, interestRate=0.08,
                      economicLifetime=15))

### Fuel Cell Electric Vehicle

#### FCEV Car

In [22]:
esM.add(fn.Conversion(esM=esM, name='FCEV_PCar', physicalUnit= r'Mio pkm/h',
                      commodityConversionFactors={'hydrogen':-1/4.7472, 'pTransport':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=15694, opexPerCapacity=15694*0.009, interestRate=0.08,
                      economicLifetime=12))

#### FCEV Truck

In [23]:
esM.add(fn.Conversion(esM=esM, name='FCEV_Truck', physicalUnit= r'Mio tkm/h',
                      commodityConversionFactors={'hydrogen':-1/8.251, 'fTransport':1},
                      hasCapacityVariable=True,
                      investPerCapacity=4283, opexPerCapacity=4283*0.009, interestRate=0.08,
                      economicLifetime=15))

### Fossil Vehicles

#### Fossil Car

In [24]:
esM.add(fn.Conversion(esM=esM, name='FossilCar', physicalUnit= r'Mio pkm/h',
                      commodityConversionFactors={'diesel':-1/3.1308, 'pTransport':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=15694, opexPerCapacity=15694*0.016, interestRate=0.08,
                      economicLifetime=12))

#### Fossil Truck

In [25]:
esM.add(fn.Conversion(esM=esM, name='FossilTruck', physicalUnit= r'Mio tkm/h',
                      commodityConversionFactors={'diesel':-1/7.938, 'fTransport':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=3342, opexPerCapacity=3342*0.016, interestRate=0.08,
                      economicLifetime=15))

## 4.5 Diesel Refinery

In [26]:
esM.add(fn.Conversion(esM=esM, name='DieselRef', physicalUnit= r'GW$_{diesel}$',
                      commodityConversionFactors={'crudeOil':-1/0.364, 'diesel':1, 'CO2':0.725},
                      hasCapacityVariable=True, 
                      investPerCapacity=1/0.364, opexPerCapacity=(1/0.364)*0.001, interestRate=0.08,
                      economicLifetime=20))

## 4.6 Power Plants

### Combined Cycle Gas Turbine

#### Natural Gas CCGT

In [27]:
esM.add(fn.Conversion(esM=esM, name='CCGT plants (NGas)', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'nGas':-1/0.65, 'CO2':0.31},
                      hasCapacityVariable=True,investPerCapacity=850, 
                      opexPerCapacity=850*0.03, opexPerOperation=0.002, interestRate=0.08,
                      economicLifetime=30))

#### H2 CCGT

In [28]:
esM.add(fn.Conversion(esM=esM, name='CCGT plants (hydrogen)', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'hydrogen':-1/0.6},
                      hasCapacityVariable=True, investPerCapacity=760, 
                      opexPerCapacity=760*0.014, opexPerOperation=0.002, interestRate=0.08,
                      economicLifetime=20))

### Fuel cell

In [29]:
esM.add(fn.Conversion(esM=esM, name='LS-SOFC', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'hydrogen':-1/0.7, 'LTHeat':0.25/0.7},
                      hasCapacityVariable=True, investPerCapacity=1210, 
                      opexPerCapacity=1210*0.008, interestRate=0.08,
                      economicLifetime=20))

### Coal power plant

In [30]:
esM.add(fn.Conversion(esM=esM, name='CoalPP', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'coal':-1/0.5, 'CO2':0.674},
                      hasCapacityVariable=True, opexPerOperation=0.0015,
                      investPerCapacity=1450, opexPerCapacity=1450*0.026, interestRate=0.08,
                      economicLifetime=40))

### Combined Heat and Power Plants

#### Coal CHP

In [31]:
esM.add(fn.Conversion(esM=esM, name='CoalCHP', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'LTHeat':0.51/0.38, 'coal':-1/0.38, 'CO2':0.886},
                      hasCapacityVariable=True, opexPerOperation=0.0051,
                      investPerCapacity=1847, opexPerCapacity=1847*0.027, interestRate=0.08,
                      economicLifetime=35))

#### Wood CHP

In [32]:
esM.add(fn.Conversion(esM=esM, name='WoodCHP', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'LTHeat':0.826/0.291, 'wood':-1/0.291},
                      hasCapacityVariable=True, opexPerOperation=0.0038,
                      investPerCapacity=3000, opexPerCapacity=3000*0.029, interestRate=0.08,
                      economicLifetime=25))

#### Natural Gas CHP

In [33]:
esM.add(fn.Conversion(esM=esM, name='nGasCHP', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'LTHeat':0.5/0.35, 'nGas':-1/0.35, 'CO2':0.575},
                      hasCapacityVariable=True, opexPerOperation=0.0015,
                      investPerCapacity=666, opexPerCapacity=666*0.041, interestRate=0.08,
                      economicLifetime=30))

#### Biogas CHP

In [34]:
esM.add(fn.Conversion(esM=esM, name='BioGasCHP', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'LTHeat':1, 'biogas':-1/0.47},
                      hasCapacityVariable=True, opexPerOperation=0.008,
                      investPerCapacity=850, opexPerCapacity=850*0.01, interestRate=0.08,
                      economicLifetime=25))

#### H2 CHP

In [35]:
esM.add(fn.Conversion(esM=esM, name='H2CHP', physicalUnit=r'GW$_{el}$',
                      commodityConversionFactors={'electricity':1, 'LTHeat':0.41/0.49, 'hydrogen':-1/0.49},
                      hasCapacityVariable=True, opexPerOperation=0.0006,
                      investPerCapacity=715, opexPerCapacity=715*0.001, interestRate=0.08,
                      economicLifetime=20))

## 4.7 Thermal power plants

#### Oil Boiler

In [36]:
esM.add(fn.Conversion(esM=esM, name='oilBoiler', physicalUnit=r'GW$_{LTHeat}$',
                      commodityConversionFactors={'crudeOil':-1/0.96, 'LTHeat':1, 'CO2':0.275},
                      hasCapacityVariable=True, 
                      investPerCapacity=330, opexPerCapacity=330*0.041, interestRate=0.08,
                      economicLifetime=20))

#### Gas Boiler

In [37]:
esM.add(fn.Conversion(esM=esM, name='gasBoiler', physicalUnit=r'GW$_{LTHeat}$',
                      commodityConversionFactors={'nGas':-1/0.96, 'LTHeat':1, 'CO2':0.21},
                      hasCapacityVariable=True, 
                      investPerCapacity=330, opexPerCapacity=330*0.012, interestRate=0.08,
                      economicLifetime=20))

#### H2 Boiler

In [38]:
esM.add(fn.Conversion(esM=esM, name='H2Boiler', physicalUnit=r'GW$_{LTHeat}$',
                      commodityConversionFactors={'hydrogen':-1/0.98, 'LTHeat':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=655, opexPerCapacity=655*0.01, interestRate=0.08,
                      economicLifetime=20))

### Heat pump

In [39]:
esM.add(fn.Conversion(esM=esM, name='Heatpump', physicalUnit=r'GW$_{LTHeat}$',
                      commodityConversionFactors={'electricity':-1/0.45, 'LTHeat':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=725, opexPerCapacity=725*0.02, interestRate=0.08,
                      economicLifetime=20))

### Heating rod

In [40]:
esM.add(fn.Conversion(esM=esM, name='Heating rod', physicalUnit=r'GW$_{LTHeat}$',
                      commodityConversionFactors={'electricity':-1/0.99, 'LTHeat':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=800, opexPerCapacity=800*0.0125, interestRate=0.08,
                      economicLifetime=30))

### Electrode boiler

In [41]:
esM.add(fn.Conversion(esM=esM, name='electrode boiler', physicalUnit=r'GW$_{Pheat}$',
                      commodityConversionFactors={'electricity':-1/0.99, 'PHeat':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=140, opexPerCapacity=140*0.02, interestRate=0.08,
                      economicLifetime=20))

### Stove

In [42]:
esM.add(fn.Conversion(esM=esM, name='woood Stove', physicalUnit=r'GW$_{LTHeat}$',
                      commodityConversionFactors={'wood':-1/0.75, 'LTHeat':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=775, opexPerCapacity=775*0.06, interestRate=0.08,
                      economicLifetime=20))

## 4.8 Electrolyzer

In [43]:
esM.add(fn.Conversion(esM=esM, name='electroylzer', physicalUnit=r'GW$_{H_{2},LHV}$',
                      commodityConversionFactors={'electricity':-1/0.7, 'hydrogen':1},
                      hasCapacityVariable=True, 
                      investPerCapacity=500, opexPerCapacity=500*0.03, interestRate=0.08,
                      economicLifetime=10))

# 5. Storages

The storages which can be used by the EnergyLand model are constructed.

## Lithium ion batteries

In [44]:
esM.add(fn.Storage(esM=esM, name='Li-ion batteries', commodity='electricity',
                   hasCapacityVariable=True, chargeEfficiency=0.99,
                   dischargeEfficiency=0.99, selfDischarge=0.004,
                   doPreciseTsaModeling=False,investPerCapacity=120, 
                   opexPerCapacity=120*0.014, opexPerChargeOperation=0.0001, 
                   interestRate=0.08, economicLifetime=10))

## Hydrogen filled salt caverns

In [45]:
esM.add(fn.Storage(esM=esM, name='H2Storage', commodity='hydrogen',
                   hasCapacityVariable=True, chargeEfficiency=0.98,
                   dischargeEfficiency=0.998, doPreciseTsaModeling=False,
                   investPerCapacity=362, opexPerCapacity=362*0.02, opexPerChargeOperation=0.0001, 
                   interestRate=0.08, economicLifetime=40))

## Heat storage

In [46]:
esM.add(fn.Storage(esM=esM, name='LTHeatstorage', commodity='LTHeat',
                   hasCapacityVariable=True, chargeEfficiency=0.95,
                   dischargeEfficiency=0.95, selfDischarge=0.0003,
                   chargeRate=1, dischargeRate=1, doPreciseTsaModeling=False,
                   investPerCapacity=147, opexPerCapacity=147*0.01, opexPerChargeOperation=0.0001,
                   interestRate=0.08, economicLifetime=20))

# 6. Sinks

Electricity, heat and transport demand are set in the following components.

## Electricity demand

In [47]:
eDemand=516
esM.add(fn.Sink(esM=esM, name='Electricity demand', commodity='electricity',
                hasCapacityVariable=False, operationRateFix=data['Electricity demand, operationRateFix']*eDemand))

## Passenger Transportation demand

In [48]:
pTdemand=867
esM.add(fn.Sink(esM=esM, name='pT_demand', commodity='pTransport',
                hasCapacityVariable=False, operationRateFix=data['T_demand, operationRateFix']*pTdemand))

## Freight Transportation demand

In [49]:
fTdemand=945.5
esM.add(fn.Sink(esM=esM, name='fT_demand', commodity='fTransport',
                hasCapacityVariable=False, operationRateFix=data['T_demand, operationRateFix']*fTdemand))

## Heat demand

### Process heat demand

In [50]:
pHeatDemand=423.75
esM.add(fn.Sink(esM=esM, name='PHeat_demand', commodity='PHeat',
                hasCapacityVariable=False, operationRateFix=data['pHeat_demand, operationRateFix']*pHeatDemand))

### Low temperature residential heat demand

In [51]:
LTHeatDemand=560.8
esM.add(fn.Sink(esM=esM, name='LTHeat_demand', commodity='LTHeat',
                hasCapacityVariable=False, operationRateFix=data['LtHeat_demand, operationRateFix']*LTHeatDemand))

## Environment

The CO2 limit is set in this component.

In [52]:
CO2limit=210000
esM.add(fn.Sink(esM=esM, name='CO2 to environment', commodity='CO2', commodityLimitID='CO2_cap',
                hasCapacityVariable=False, yearlyLimit=CO2limit))

# 7. Optimization of EnergyLand

In [54]:
myopicResults = fn.optimizeSimpleMyopic(esM, startYear=2020, endYear=2050, nbOfRepresentedYears=10,
                    timeSeriesAggregation=True, numberOfTypicalPeriods = 12, numberOfTimeStepsPerPeriod=24,
                    logFileName='', threads=3, solver='gurobi', timeLimit=None, 
                    optimizationSpecs='', warmstart=False, 
                    CO2Reference=366000, CO2ReductionTargets=[50,70,90,100], saveResults=False, trackESMs=True)

Number of optimization runs:  4
Number of years represented by one optimization:  10

Clustering time series data with 12 typical periods and 24 time steps per period...
		(0.2845 sec)

Time series aggregation specifications:
Number of typical periods:12, number of time steps per periods:24

Declaring sets, variables and constraints for SourceSinkModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.1694 sec)

Declaring sets, variables and constraints for ConversionModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.2359 sec)

Declaring sets, variables and constraints for StorageModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.2232 sec)

Declaring shared potential constraint...
		(0.0000 sec)

Declaring commodity balances...
		(0.2473 sec)

Declaring objective function...
		(0.2032 sec)

Using license file C:\Users\t.schoeb\gurobi.lic
Academic license - for non-commercial use only
Read LP format model from file C:\Users\T30F7~1.SCH\AppData\Local\Temp\tmp0n6yj1b7.pyomo.lp
Reading time = 0.11 seconds
x31515: 23232 rows, 16827 columns, 66345 nonzeros
Changed value of parameter QCPDual to 1
   Prev: 0  Min: 0  Max: 1  Default: 0
Changed value of parameter Threads to 3
   Prev: 0  Min: 0  Max: 1024  Default: 0
Changed value of parameter logfile to log_2020
   Prev:   Default:
Gurobi Optimizer version 9.0.2 build v9.0.2rc0 (win64)
Optimize a model with 23232 rows, 16827 columns and 66345 nonzeros
Model fingerprint: 0xa79d4def
Coefficient statistics:
  Matrix range     [4e-06, 7e+01]
  Objective range  [1e-03, 2e+03]
  Bounds range     [7e-01, 6e+02]
  RHS range        [4e-01, 2e+05]

Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...

Presolve removed 7097 rows and 5589 columns
Presolve time: 0.05s
Presolved: 16135 rows, 11238 columns, 59511 nonzeros

Ordering time: 0.18s

Barrier statistics:
 Dense cols : 66
 Free vars  : 180
 AA' NZ     : 1.717e+05
 Factor NZ  : 7.643e+05 (roughly 17 MBytes of memory)
 Factor Ops : 1.067e+08 (less than 1 second per iteration)
 Threads    : 2

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.91962026e+07 -9.61319201e+04  2.88e+05 1.32e+02  2.17e+05     0s
   1   1.70952416e+07 -1.84428543e+07  1.94e+05 6.16e+01  8.72e+04     0s
   2   1.07397324e+07 -2.25686975e+07  5.41e+04 1.54e+01  2.50e+04     0s
   3   7.55237348e+06 -1.88213128e+07  1.69e+04 2.98e+00  7.25e+03     0s
   4   4.35481842e+06 -1.27991027e+07  4.65e+03 9.87e-01  2.35e+03     0s
   5   3.07902823e+06 -8.38239992e+06  2.26e+03 4.51e-01  1.18e+03     1s
   6   2.24429046e+06 -4.07893213e+06  1.21e+03 1.51e-01  5.41e+02     1s
   7   1.50650194e+06 -2.68913322e+06  5.44e+02 8.26e-02  2.85e+02     1s
   8   9.80079123e+05 -1.31226678e+06  1.79e+02 3.39e-02  1.22e+02     1s
   9   7.39897065e+05 -1.76136252e+05  7.31e+01 8.07e-03  4.25e+01     1s
  10   6.08267263e+05  1.12715680e+05  3.15e+01 4.69e-03  2.14e+01     1s
  11   5.32289747e+05  3.14245359e+05  1.02e+01 9.56e-04  8.96e+00     1s
  12   4.95271910e+05  3.63422015e+05  6.58e+00 4.52e-04  5.34e+00     1s
  13   4.74234078e+05  3.84492769e+05  4.57e+00 2.76e-04  3.61e+00     1s
  14   4.56754875e+05  3.98218337e+05  2.97e+00 1.82e-04  2.34e+00     1s
  15   4.40078193e+05  4.07729025e+05  1.48e+00 1.61e-04  1.29e+00     1s
  16   4.33713320e+05  4.12761207e+05  9.69e-01 1.27e-04  8.32e-01     1s
  17   4.30194124e+05  4.15240508e+05  7.11e-01 9.09e-05  5.93e-01     1s
  18   4.27518739e+05  4.16389446e+05  5.24e-01 6.95e-05  4.41e-01     1s
  19   4.24837373e+05  4.17343582e+05  3.40e-01 5.14e-05  2.97e-01     1s
  20   4.22816713e+05  4.17881453e+05  2.04e-01 4.38e-05  1.95e-01     1s
  21   4.22623755e+05  4.18138932e+05  1.93e-01 4.05e-05  1.78e-01     1s
  22   4.21370642e+05  4.18840209e+05  1.07e-01 3.27e-05  1.00e-01     1s
  23   4.20810481e+05  4.19165256e+05  7.01e-02 3.21e-05  6.50e-02     1s
  24   4.20480295e+05  4.19419991e+05  4.91e-02 2.67e-05  4.19e-02     1s
  25   4.20036613e+05  4.19536478e+05  2.17e-02 2.25e-05  1.97e-02     1s
  26   4.19821007e+05  4.19600955e+05  8.89e-03 1.08e-05  8.69e-03     1s
  27   4.19737313e+05  4.19628841e+05  4.06e-03 9.14e-06  4.28e-03     1s
  28   4.19715760e+05  4.19637951e+05  2.96e-03 9.02e-06  3.07e-03     1s
  29   4.19676396e+05  4.19643000e+05  9.77e-04 9.71e-06  1.32e-03     1s
  30   4.19657559e+05  4.19652455e+05  8.34e-05 2.30e-05  2.01e-04     1s
  31   4.19654449e+05  4.19653756e+05  8.14e-06 1.02e-05  2.73e-05     1s
  32   4.19654180e+05  4.19653968e+05  2.61e-06 2.22e-06  8.35e-06     1s
  33   4.19654158e+05  4.19653991e+05  2.17e-06 1.49e-06  6.58e-06     1s
  34   4.19654158e+05  4.19653991e+05  2.17e-06 1.49e-06  6.58e-06     1s
  35   4.19654158e+05  4.19653991e+05  7.47e-06 1.49e-06  6.58e-06     1s
  36   4.19654158e+05  4.19653991e+05  7.54e-06 1.49e-06  6.57e-06     1s
  37   4.19654158e+05  4.19653991e+05  9.00e-06 1.49e-06  6.57e-06     1s
  38   4.19654158e+05  4.19653991e+05  9.00e-06 1.49e-06  6.56e-06     1s
  39   4.19654158e+05  4.19653991e+05  9.00e-06 1.49e-06  6.56e-06     2s
  40   4.19654158e+05  4.19653991e+05  9.00e-06 1.49e-06  6.56e-06     2s
  41   4.19654158e+05  4.19653991e+05  9.00e-06 1.49e-06  6.55e-06     2s
  42   4.19654158e+05  4.19653991e+05  9.00e-06 1.49e-06  6.55e-06     2s
  43   4.19654158e+05  4.19653991e+05  9.00e-06 1.49e-06  6.55e-06     2s

Barrier performed 43 iterations in 1.64 seconds
Sub-optimal termination - objective 4.19654158e+05

Crossover log...

       0 DPushes remaining with DInf 0.0000000e+00                 2s

    6758 PPushes remaining with PInf 6.4885027e-04                 2s
       0 PPushes remaining with PInf 1.9943855e-02                 3s

  Push phase complete: Pinf 1.9943855e-02, Dinf 2.5968219e+03      3s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11822    4.1965407e+05   0.000000e+00   2.596822e+03      3s
   12104    4.1965404e+05   0.000000e+00   0.000000e+00      3s

Solved with barrier
Solved in 12104 iterations and 2.87 seconds
Optimal objective  4.196540397e+05

Status: ok
Return code: 0
Message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Termination condition: optimal
Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Wall time: 2.8717479705810547
Error rc: 0
Time: 3.4966094493865967


Name: x31515_copy
Lower bound: 419654.0396537557
Upper bound: 419654.0396537557
Number of objectives: 1
Number of constraints: 23232
Number of variables: 16827
Number of binary variables: 0
Number of integer variables: 0
Number of continuous variables: 16827
Number of nonzeros: 66345
Sense: minimize

Solve time: 4.705484628677368 sec.

Processing optimization output...
for SourceSinkModel ...(0.7431sec)
for ConversionModel ...(0.8463sec)
for StorageModel ...  (1.5840sec)
		(3.1734 sec)


Clustering time series data with 12 typical periods and 24 time steps per period...
		(0.4007 sec)

Time series aggregation specifications:
Number of typical periods:12, number of time steps per periods:24

Declaring sets, variables and constraints for SourceSinkModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.2539 sec)

Declaring sets, variables and constraints for ConversionModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.6637 sec)

Declaring sets, variables and constraints for StorageModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.3793 sec)

Declaring shared potential constraint...
		(0.0000 sec)

Declaring commodity balances...
		(0.3449 sec)

Declaring objective function...
		(0.1536 sec)

Using license file C:\Users\t.schoeb\gurobi.lic
Academic license - for non-commercial use only
Read LP format model from file C:\Users\T30F7~1.SCH\AppData\Local\Temp\tmp90w0y8rk.pyomo.lp
Reading time = 0.22 seconds
x50809: 36162 rows, 27193 columns, 114522 nonzeros
Changed value of parameter QCPDual to 1
   Prev: 0  Min: 0  Max: 1  Default: 0
Changed value of parameter Threads to 3
   Prev: 0  Min: 0  Max: 1024  Default: 0
Changed value of parameter logfile to log_2030
   Prev:   Default:
Gurobi Optimizer version 9.0.2 build v9.0.2rc0 (win64)
Optimize a model with 36162 rows, 27193 columns and 114522 nonzeros
Model fingerprint: 0x3974701f
Coefficient statistics:
  Matrix range     [4e-06, 4e+01]
  Objective range  [1e-03, 2e+03]
  Bounds range     [7e-01, 6e+02]
  RHS range        [3e-01, 1e+05]

Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...

Presolve removed 18633 rows and 12363 columns
Presolve time: 0.08s
Presolved: 17529 rows, 14830 columns, 74479 nonzeros

Ordering time: 0.23s

Barrier statistics:
 Dense cols : 70
 Free vars  : 180
 AA' NZ     : 2.381e+05
 Factor NZ  : 1.238e+06 (roughly 23 MBytes of memory)
 Factor Ops : 2.446e+08 (less than 1 second per iteration)
 Threads    : 2

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.12056655e+07 -1.33561641e+07  2.12e+05 6.73e+01  2.92e+05     0s
   1   2.94974290e+07 -2.21183624e+07  1.48e+05 6.93e+01  1.28e+05     0s
   2   2.09275009e+07 -2.73555719e+07  7.46e+04 1.16e+01  5.42e+04     0s
   3   9.14110162e+06 -2.56447699e+07  9.24e+03 1.20e+00  7.36e+03     1s
   4   4.70280105e+06 -1.78723908e+07  2.19e+03 3.35e-01  2.05e+03     1s
   5   3.53998844e+06 -9.69461610e+06  1.30e+03 9.75e-02  1.01e+03     1s
   6   1.86853582e+06 -3.47775787e+06  3.45e+02 1.30e-02  2.74e+02     1s
   7   1.27172027e+06 -1.39764734e+06  1.52e+02 1.92e-03  1.15e+02     1s
   8   1.08246479e+06 -6.96520241e+05  1.02e+02 1.80e-03  7.09e+01     1s
   9   7.82748959e+05 -7.99543248e+04  3.47e+01 1.42e-03  2.96e+01     1s
  10   6.59933995e+05  2.12450510e+04  1.97e+01 2.68e-04  2.09e+01     1s
  11   5.82569375e+05  2.18694774e+05  1.07e+01 2.17e-04  1.15e+01     1s
  12   5.69506453e+05  2.93750216e+05  9.40e+00 1.79e-04  8.67e+00     1s
  13   5.30442050e+05  3.40064678e+05  5.94e+00 1.52e-04  5.89e+00     1s
  14   5.01566250e+05  3.89399539e+05  3.62e+00 1.16e-04  3.43e+00     1s
  15   4.81416479e+05  4.11967475e+05  2.21e+00 9.99e-05  2.11e+00     1s
  16   4.71207204e+05  4.25121101e+05  1.56e+00 9.54e-05  1.39e+00     1s
  17   4.57859319e+05  4.35007461e+05  7.61e-01 9.65e-05  6.87e-01     1s
  18   4.53311067e+05  4.39311849e+05  5.01e-01 8.57e-05  4.20e-01     1s
  19   4.49951879e+05  4.41913845e+05  3.10e-01 6.48e-05  2.41e-01     1s
  20   4.47914517e+05  4.42769248e+05  2.04e-01 5.12e-05  1.54e-01     1s
  21   4.47798054e+05  4.42860608e+05  1.98e-01 4.97e-05  1.48e-01     1s
  22   4.46712074e+05  4.43117026e+05  1.42e-01 4.40e-05  1.08e-01     1s
  23   4.46140918e+05  4.43388367e+05  1.13e-01 3.70e-05  8.25e-02     1s
  24   4.44860111e+05  4.43537153e+05  4.90e-02 5.03e-05  3.96e-02     1s
  25   4.44225754e+05  4.43696269e+05  1.77e-02 5.88e-05  1.58e-02     1s
  26   4.44056320e+05  4.43737933e+05  9.82e-03 5.24e-05  9.51e-03     1s
  27   4.43979186e+05  4.43780360e+05  6.30e-03 3.81e-05  5.94e-03     1s
  28   4.43928386e+05  4.43817205e+05  4.15e-03 1.92e-05  3.32e-03     1s
  29   4.43883925e+05  4.43822425e+05  2.29e-03 2.04e-05  1.84e-03     1s
  30   4.43853252e+05  4.43827005e+05  9.70e-04 2.25e-05  7.85e-04     1s
  31   4.43838699e+05  4.43828530e+05  3.47e-04 2.23e-05  3.04e-04     1s
  32   4.43832895e+05  4.43829225e+05  1.17e-04 1.96e-05  1.10e-04     1s
  33   4.43832099e+05  4.43829458e+05  8.61e-05 1.06e-05  7.90e-05     2s
  34   4.43830771e+05  4.43829641e+05  3.74e-05 6.84e-06  3.38e-05     2s
  35   4.43830409e+05  4.43829725e+05  2.35e-05 2.04e-06  2.05e-05     2s
  36   4.43830063e+05  4.43829748e+05  1.04e-05 1.09e-06  9.41e-06     2s
  37   4.43829882e+05  4.43829766e+05  3.56e-06 3.42e-07  3.46e-06     2s
  38   4.43829814e+05  4.43829775e+05  1.17e-06 4.40e-08  1.15e-06     2s
  39   4.43829787e+05  4.43829777e+05  1.61e-06 2.07e-08  2.84e-07     2s
  40   4.43829786e+05  4.43829777e+05  1.48e-06 3.65e-07  2.56e-07     2s
  41   4.43829781e+05  4.43829778e+05  5.70e-06 1.93e-05  9.41e-08     2s
  42   4.43829778e+05  4.43829778e+05  1.72e-06 1.19e-06  5.66e-09     2s

Barrier solved model in 42 iterations and 1.88 seconds
Optimal objective 4.43829778e+05

Crossover log...

       0 DPushes remaining with DInf 0.0000000e+00                 2s

     931 PPushes remaining with PInf 0.0000000e+00                 2s
       0 PPushes remaining with PInf 0.0000000e+00                 2s

  Push phase complete: Pinf 0.0000000e+00, Dinf 2.0685377e-03      2s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
    5147    4.4382978e+05   0.000000e+00   2.068538e-03      2s
    5192    4.4382978e+05   0.000000e+00   0.000000e+00      2s

Solved with barrier
Solved in 5192 iterations and 2.18 seconds
Optimal objective  4.438297777e+05

Status: ok
Return code: 0
Message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Termination condition: optimal
Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Wall time: 2.176250457763672
Error rc: 0
Time: 2.9894649982452393


Name: x50809_copy
Lower bound: 443829.77771342936
Upper bound: 443829.77771342936
Number of objectives: 1
Number of constraints: 36162
Number of variables: 27193
Number of binary variables: 0
Number of integer variables: 0
Number of continuous variables: 27193
Number of nonzeros: 114522
Sense: minimize

Solve time: 5.007252216339111 sec.

Processing optimization output...
for SourceSinkModel ...(0.6842sec)
for ConversionModel ...(1.3727sec)
for StorageModel ...  (1.9067sec)
		(3.9636 sec)


Clustering time series data with 12 typical periods and 24 time steps per period...
		(0.3019 sec)

Time series aggregation specifications:
Number of typical periods:12, number of time steps per periods:24

Declaring sets, variables and constraints for SourceSinkModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.5336 sec)

Declaring sets, variables and constraints for ConversionModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.3544 sec)

Declaring sets, variables and constraints for StorageModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.4631 sec)

Declaring shared potential constraint...
		(0.0000 sec)

Declaring commodity balances...
		(0.3724 sec)

Declaring objective function...
		(0.1614 sec)

Using license file C:\Users\t.schoeb\gurobi.lic
Academic license - for non-commercial use only
Read LP format model from file C:\Users\T30F7~1.SCH\AppData\Local\Temp\tmp2x75_w5l.pyomo.lp
Reading time = 0.23 seconds
x56699: 40742 rows, 30491 columns, 131880 nonzeros
Changed value of parameter QCPDual to 1
   Prev: 0  Min: 0  Max: 1  Default: 0
Changed value of parameter Threads to 3
   Prev: 0  Min: 0  Max: 1024  Default: 0
Changed value of parameter logfile to log_2040
   Prev:   Default:
Gurobi Optimizer version 9.0.2 build v9.0.2rc0 (win64)
Optimize a model with 40742 rows, 30491 columns and 131880 nonzeros
Model fingerprint: 0xecbe0804
Coefficient statistics:
  Matrix range     [4e-06, 4e+01]
  Objective range  [1e-03, 2e+03]
  Bounds range     [7e-01, 6e+02]
  RHS range        [1e-02, 4e+04]

Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...

Presolve removed 23213 rows and 15949 columns
Presolve time: 0.06s
Presolved: 17529 rows, 14542 columns, 74191 nonzeros

Ordering time: 0.21s

Barrier statistics:
 Dense cols : 70
 Free vars  : 180
 AA' NZ     : 2.381e+05
 Factor NZ  : 1.238e+06 (roughly 23 MBytes of memory)
 Factor Ops : 2.446e+08 (less than 1 second per iteration)
 Threads    : 2

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   8.93904274e+06 -4.88940374e+06  8.19e+04 7.06e+01  8.30e+04     0s
   1   7.81144736e+06 -1.62452009e+07  5.54e+04 6.48e+01  3.57e+04     0s
   2   4.75105338e+06 -1.83882563e+07  1.60e+04 1.19e+01  1.00e+04     0s
   3   2.83037873e+06 -1.15813557e+07  2.70e+03 2.50e+00  2.03e+03     0s
   4   2.10455225e+06 -5.91998421e+06  1.24e+03 8.79e-01  8.96e+02     1s
   5   1.43621496e+06 -2.24092530e+06  4.45e+02 1.69e-01  3.08e+02     1s
   6   1.13903936e+06 -1.09249543e+06  2.41e+02 8.15e-02  1.62e+02     1s
   7   1.00634608e+06 -6.33609652e+05  1.62e+02 4.99e-02  1.09e+02     1s
   8   8.79348720e+05 -1.38760674e+05  9.14e+01 2.50e-02  6.01e+01     1s
   9   7.52730000e+05  1.74868977e+05  2.98e+01 1.27e-02  2.69e+01     1s
  10   6.91824616e+05  4.59224815e+05  1.27e+01 3.92e-03  9.99e+00     1s
  11   6.71423728e+05  5.14401385e+05  9.02e+00 2.42e-03  6.63e+00     1s
  12   6.53654256e+05  5.38246745e+05  6.17e+00 1.77e-03  4.75e+00     1s
  13   6.40152568e+05  5.56502799e+05  4.16e+00 1.27e-03  3.36e+00     1s

  14   6.31913338e+05  5.81265935e+05  3.05e+00 6.32e-04  2.03e+00     1s
  15   6.21526078e+05  5.95037944e+05  1.65e+00 4.48e-04  1.04e+00     1s
  16   6.13636366e+05  6.01155758e+05  7.42e-01 2.08e-04  4.82e-01     1s
  17   6.11289689e+05  6.04075575e+05  4.94e-01 7.89e-05  2.79e-01     1s
  18   6.09094110e+05  6.05348532e+05  2.72e-01 9.18e-05  1.44e-01     1s
  19   6.07978705e+05  6.05760055e+05  1.64e-01 9.75e-05  8.47e-02     1s
  20   6.07778874e+05  6.05956499e+05  1.42e-01 1.01e-04  6.94e-02     1s
  21   6.07609898e+05  6.05995925e+05  1.26e-01 1.11e-04  6.14e-02     1s
  22   6.07030136e+05  6.06099389e+05  6.85e-02 1.31e-04  3.51e-02     1s
  23   6.06684855e+05  6.06175628e+05  3.52e-02 1.21e-04  1.90e-02     1s
  24   6.06511448e+05  6.06224948e+05  1.92e-02 8.41e-05  1.06e-02     1s
  25   6.06431997e+05  6.06253149e+05  1.17e-02 5.34e-05  6.59e-03     1s
  26   6.06384990e+05  6.06265484e+05  7.67e-03 3.85e-05  4.40e-03     1s
  27   6.06369191e+05  6.06271753e+05  6.34e-03 3.58e-05  3.59e-03     1s
  28   6.06311024e+05  6.06284867e+05  1.43e-03 3.14e-05  9.41e-04     1s
  29   6.06297016e+05  6.06289529e+05  3.58e-04 3.48e-05  2.65e-04     1s
  30   6.06293650e+05  6.06291473e+05  1.06e-04 2.07e-05  7.66e-05     1s
  31   6.06293050e+05  6.06291749e+05  6.39e-05 9.87e-06  4.58e-05     1s
  32   6.06292898e+05  6.06291950e+05  5.34e-05 3.81e-06  3.39e-05     1s
  33   6.06292324e+05  6.06292035e+05  1.40e-05 1.34e-06  1.01e-05     1s
  34   6.06292323e+05  6.06292035e+05  1.40e-05 1.34e-06  1.01e-05     1s
  35   6.06292323e+05  6.06292035e+05  1.40e-05 1.34e-06  1.01e-05     2s
  36   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.04e-06     2s
  37   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  38   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  39   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  40   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  41   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  42   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  43   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  44   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  45   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s
  46   6.06292230e+05  6.06292054e+05  9.46e-06 8.63e-07  6.03e-06     2s

Barrier performed 46 iterations in 2.03 seconds
Sub-optimal termination - objective 6.06292324e+05

Crossover log...

       0 DPushes remaining with DInf 0.0000000e+00                 2s

    8443 PPushes remaining with PInf 8.2269328e-06                 2s
       0 PPushes remaining with PInf 8.7129883e-02                 3s

  Push phase complete: Pinf 8.7129883e-02, Dinf 1.8203949e+03      3s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
   12462    6.0629214e+05   0.000000e+00   1.820395e+03      3s
   13127    6.0629210e+05   0.000000e+00   0.000000e+00      3s

Solved with barrier
Solved in 13127 iterations and 2.88 seconds
Optimal objective  6.062920995e+05

Status: ok
Return code: 0
Message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Termination condition: optimal
Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Wall time: 2.8857555389404297
Error rc: 0
Time: 3.849695920944214


Name: x56699_copy
Lower bound: 606292.099514909
Upper bound: 606292.099514909
Number of objectives: 1
Number of constraints: 40742
Number of variables: 30491
Number of binary variables: 0
Number of integer variables: 0
Number of continuous variables: 30491
Number of nonzeros: 131880
Sense: minimize

Solve time: 6.206944942474365 sec.

Processing optimization output...
for SourceSinkModel ...(0.6394sec)
for ConversionModel ...(1.5286sec)
for StorageModel ...  (2.0303sec)
		(4.1983 sec)


Clustering time series data with 12 typical periods and 24 time steps per period...
		(0.2929 sec)

Time series aggregation specifications:
Number of typical periods:12, number of time steps per periods:24

Declaring sets, variables and constraints for SourceSinkModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.2014 sec)

Declaring sets, variables and constraints for ConversionModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.3627 sec)

Declaring sets, variables and constraints for StorageModel
	declaring sets...
	declaring variables...
	declaring constraints...
		(0.5146 sec)

Declaring shared potential constraint...
		(0.0000 sec)

Declaring commodity balances...
		(0.3725 sec)

Declaring objective function...
		(0.1627 sec)

Using license file C:\Users\t.schoeb\gurobi.lic
Academic license - for non-commercial use only
Read LP format model from file C:\Users\T30F7~1.SCH\AppData\Local\Temp\tmp2emc9d07.pyomo.lp
Reading time = 0.25 seconds
x59699: 43872 rows, 32339 columns, 142023 nonzeros
Changed value of parameter QCPDual to 1
   Prev: 0  Min: 0  Max: 1  Default: 0
Changed value of parameter Threads to 3
   Prev: 0  Min: 0  Max: 1024  Default: 0
Changed value of parameter logfile to log_2050
   Prev:   Default:
Gurobi Optimizer version 9.0.2 build v9.0.2rc0 (win64)
Optimize a model with 43872 rows, 32339 columns and 142023 nonzeros
Model fingerprint: 0xc7e59322
Coefficient statistics:
  Matrix range     [4e-06, 4e+01]
  Objective range  [1e-03, 2e+03]
  Bounds range     [7e-01, 6e+02]
  RHS range        [1e-04, 6e+03]

Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...

Presolve removed 24956 rows and 17667 columns
Presolve time: 0.09s
Presolved: 18916 rows, 14672 columns, 78731 nonzeros

Ordering time: 0.27s

Barrier statistics:
 Dense cols : 80
 Free vars  : 180
 AA' NZ     : 2.866e+05
 Factor NZ  : 1.496e+06 (roughly 26 MBytes of memory)
 Factor Ops : 3.348e+08 (less than 1 second per iteration)
 Threads    : 2

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   3.80172571e+08 -2.04612359e+08  9.98e+04 7.49e+01  4.08e+06     0s
   1   3.65560884e+08 -3.15268373e+08  7.24e+04 6.24e+01  1.86e+06     1s
   2   2.25499597e+08 -3.27092394e+08  1.96e+04 1.29e+01  5.02e+05     1s
   3   1.30888219e+08 -2.50523497e+08  4.75e+03 1.83e+00  1.19e+05     1s
   4   5.84384773e+07 -1.45752966e+08  9.59e+02 4.82e-01  2.77e+04     1s
   5   3.09918739e+07 -6.19119143e+07  3.01e+02 1.12e-01  8.84e+03     1s
   6   1.73246340e+07 -1.95754007e+07  1.28e+02 1.40e-02  3.34e+03     1s
   7   5.51941417e+06 -7.10284523e+06  2.93e+01 1.64e-03  8.06e+02     1s
   8   3.07593392e+06 -2.40769925e+06  1.14e+01 9.12e-04  3.05e+02     1s
   9   2.13611185e+06 -8.32331739e+05  6.22e+00 9.84e-04  1.57e+02     1s
  10   1.55312516e+06  1.96590302e+05  3.23e+00 9.62e-04  7.11e+01     1s
  11   1.20333935e+06  5.67037416e+05  1.32e+00 6.70e-04  3.01e+01     1s
  12   1.06098699e+06  7.14589167e+05  6.87e-01 6.36e-04  1.56e+01     1s
  13   1.00905289e+06  7.42645796e+05  4.48e-01 5.85e-04  1.12e+01     1s
  14   9.80094797e+05  7.84035749e+05  3.37e-01 4.89e-04  8.18e+00     1s
  15   9.33649787e+05  8.33965688e+05  1.65e-01 3.18e-04  4.02e+00     1s
  16   9.11146139e+05  8.67178370e+05  7.77e-02 1.79e-04  1.78e+00     1s
  17   9.01661851e+05  8.83825571e+05  4.31e-02 1.60e-04  7.94e-01     1s
  18   8.92354522e+05  8.86228954e+05  1.42e-02 1.30e-04  2.68e-01     1s
  19   8.89861272e+05  8.86994535e+05  6.63e-03 1.33e-04  1.25e-01     1s
  20   8.88894127e+05  8.87195031e+05  3.84e-03 1.63e-04  7.33e-02     1s
  21   8.88629319e+05  8.87328522e+05  3.07e-03 1.80e-04  5.55e-02     1s
  22   8.88536469e+05  8.87329306e+05  2.83e-03 1.79e-04  5.14e-02     1s
  23   8.88332304e+05  8.87363523e+05  2.29e-03 1.65e-04  4.11e-02     1s
  24   8.88220218e+05  8.87370637e+05  1.99e-03 1.58e-04  3.59e-02     1s
  25   8.88054176e+05  8.87392934e+05  1.56e-03 1.35e-04  2.78e-02     1s
  26   8.87912610e+05  8.87400272e+05  1.18e-03 1.26e-04  2.15e-02     1s
  27   8.87857727e+05  8.87446586e+05  1.03e-03 8.12e-05  1.82e-02     1s
  28   8.87740647e+05  8.87459443e+05  7.04e-04 7.65e-05  1.27e-02     1s
  29   8.87700568e+05  8.87455719e+05  5.76e-04 7.14e-05  1.07e-02     2s
  30   8.87642715e+05  8.87464890e+05  3.98e-04 5.96e-05  7.61e-03     2s
  31   8.87608727e+05  8.87468182e+05  3.02e-04 5.56e-05  5.98e-03     2s
  32   8.87591210e+05  8.87478188e+05  2.46e-04 4.17e-05  4.79e-03     2s

  33   8.87571224e+05  8.87482939e+05  1.89e-04 4.11e-05  3.71e-03     2s
  34   8.87556186e+05  8.87485911e+05  1.40e-04 4.13e-05  2.93e-03     2s
  35   8.87513625e+05  8.87493195e+05  2.61e-05 4.60e-05  8.03e-04     2s
  36   8.87504744e+05  8.87494550e+05  1.17e-05 3.27e-05  3.89e-04     2s
  37   8.87499691e+05  8.87495891e+05  3.81e-06 1.29e-05  1.40e-04     2s
  38   8.87498263e+05  8.87496498e+05  1.64e-06 7.63e-06  6.39e-05     2s
  39   8.87497894e+05  8.87496781e+05  1.13e-06 3.39e-06  4.11e-05     2s
  40   8.87497668e+05  8.87496846e+05  8.19e-07 2.54e-06  3.03e-05     2s
  41   8.87497461e+05  8.87496907e+05  5.39e-07 1.76e-06  2.03e-05     2s
  42   8.87497277e+05  8.87496982e+05  2.84e-07 7.46e-07  1.08e-05     2s
  43   8.87497197e+05  8.87497014e+05  1.81e-07 3.26e-07  6.74e-06     2s
  44   8.87497172e+05  8.87497021e+05  1.53e-07 2.63e-07  5.59e-06     2s
  45   8.87497142e+05  8.87497028e+05  1.13e-07 1.96e-07  4.19e-06     2s
  46   8.87497113e+05  8.87497034e+05  7.65e-08 1.55e-07  2.91e-06     2s
  47   8.87497112e+05  8.87497035e+05  7.48e-08 1.43e-07  2.81e-06     2s
  48   8.87497087e+05  8.87497040e+05  4.79e-08 1.10e-07  1.71e-06     2s
  49   8.87497072e+05  8.87497045e+05  2.56e-08 6.05e-08  1.01e-06     2s
  50   8.87497068e+05  8.87497047e+05  2.06e-08 3.54e-08  7.74e-07     2s
  51   8.87497068e+05  8.87497047e+05  6.93e-08 3.49e-08  7.59e-07     2s
  52   8.87497061e+05  8.87497047e+05  4.70e-08 3.10e-08  4.79e-07     3s
  53   8.87497060e+05  8.87497049e+05  4.35e-08 1.84e-08  4.22e-07     3s
  54   8.87497060e+05  8.87497049e+05  4.15e-08 1.70e-08  4.01e-07     3s
  55   8.87497059e+05  8.87497049e+05  4.11e-08 1.56e-08  3.92e-07     3s

Barrier solved model in 55 iterations and 2.69 seconds
Optimal objective 8.87497059e+05

Crossover log...

       0 DPushes remaining with DInf 0.0000000e+00                 3s

    5301 PPushes remaining with PInf 1.4544714e-02                 3s
       0 PPushes remaining with PInf 3.5059407e-01                 3s

  Push phase complete: Pinf 3.5059407e-01, Dinf 5.6004815e+03      3s

Iteration    Objective       Primal Inf.    Dual Inf.      Time
   10001    8.8749705e+05   0.000000e+00   5.600481e+03      3s
   10516    8.8749705e+05   0.000000e+00   0.000000e+00      3s

Solved with barrier
Solved in 10516 iterations and 3.08 seconds
Optimal objective  8.874970503e+05

Status: ok
Return code: 0
Message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Termination condition: optimal
Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
Wall time: 3.0908775329589844
Error rc: 0
Time: 3.890543222427368


Name: x59699_copy
Lower bound: 887497.0502821881
Upper bound: 887497.0502821881
Number of objectives: 1
Number of constraints: 43872
Number of variables: 32339
Number of binary variables: 0
Number of integer variables: 0
Number of continuous variables: 32339
Number of nonzeros: 142023
Sense: minimize

Solve time: 6.589635848999023 sec.

Processing optimization output...
for SourceSinkModel ...(0.6357sec)
for ConversionModel ...(1.5430sec)
for StorageModel ...  (2.1323sec)
		(4.3110 sec)

# 8. Results

In [55]:
esM2020 = myopicResults['ESM_2020']
esM2030 = myopicResults['ESM_2030']
esM2040 = myopicResults['ESM_2040']
esM2050 = myopicResults['ESM_2050']

In [56]:
esM2020.getOptimizationSummary("SourceSinkModel", outputLevel=2).loc['PV']

                          EnergyLand
Property  Unit
TAC       [1e6 Euro/a]       23590.4
capacity  [GW$_{el}$]            244
capexCap  [1e6 Euro/a]       19881.6
invest    [1e6 Euro]          195200
operation [GW$_{el}$*h/a]     276865
opexCap   [1e6 Euro/a]        3708.8

In [57]:
i = ['PV_stock_2020' , 'PV']
esM2030.getOptimizationSummary("SourceSinkModel", outputLevel=2).loc[i]

                                        EnergyLand
Component     Property  Unit
PV            TAC       [1e6 Euro/a]       17534.9
              capacity  [GW$_{el}$]        181.368
              capexCap  [1e6 Euro/a]       14778.2
              invest    [1e6 Euro]          145094
              operation [GW$_{el}$*h/a]     159993
              opexCap   [1e6 Euro/a]       2756.79
PV_stock_2020 TAC       [1e6 Euro/a]       23590.4
              capacity  [GW$_{el}$]            244
              capexCap  [1e6 Euro/a]       19881.6
              invest    [1e6 Euro]          195200
              operation [GW$_{el}$*h/a]     287410
              opexCap   [1e6 Euro/a]        3708.8

In [58]:
i.extend(['PV_stock_2030'])
print(i)
esM2040.getOptimizationSummary("SourceSinkModel", outputLevel=2).loc[i]

['PV_stock_2020', 'PV', 'PV_stock_2030']

                                        EnergyLand
Component     Property  Unit
PV            TAC       [1e6 Euro/a]       23590.4
              capacity  [GW$_{el}$]            244
              capexCap  [1e6 Euro/a]       19881.6
              invest    [1e6 Euro]          195200
              operation [GW$_{el}$*h/a]     262766
              opexCap   [1e6 Euro/a]        3708.8
PV_stock_2030 TAC       [1e6 Euro/a]       17534.9
              capacity  [GW$_{el}$]        181.368
              capexCap  [1e6 Euro/a]       14778.2
              invest    [1e6 Euro]          145094
              operation [GW$_{el}$*h/a]     225327
              opexCap   [1e6 Euro/a]       2756.79

In [59]:
i.extend(['PV_stock_2040'])
esM2050.getOptimizationSummary("SourceSinkModel", outputLevel=2).loc[i]

                                        EnergyLand
Component     Property  Unit
PV            TAC       [1e6 Euro/a]       23590.4
              capacity  [GW$_{el}$]            244
              capexCap  [1e6 Euro/a]       19881.6
              invest    [1e6 Euro]          195200
              operation [GW$_{el}$*h/a]    55241.2
              opexCap   [1e6 Euro/a]        3708.8
PV_stock_2040 TAC       [1e6 Euro/a]       23590.4
              capacity  [GW$_{el}$]            244
              capexCap  [1e6 Euro/a]       19881.6
              invest    [1e6 Euro]          195200
              operation [GW$_{el}$*h/a]     242403
              opexCap   [1e6 Euro/a]        3708.8

In [60]:
esM2020.getOptimizationSummary("ConversionModel", outputLevel=2).loc['CCGT plants (NGas)']

                          EnergyLand
Property  Unit
TAC       [1e6 Euro/a]       5712.99
capacity  [GW$_{el}$]        54.8474
capexCap  [1e6 Euro/a]       4141.16
invest    [1e6 Euro]         46620.3
operation [GW$_{el}$*h/a]    86610.4
opexCap   [1e6 Euro/a]       1398.61
opexOp    [1e6 Euro/a]       173.221

In [61]:
i = ['CCGT plants (NGas)','CCGT plants (NGas)_stock_2020']
esM2030.getOptimizationSummary("ConversionModel", outputLevel=2).loc[i]

                                                        EnergyLand
Component                     Property  Unit
CCGT plants (NGas)_stock_2020 TAC       [1e6 Euro/a]       5649.82
                              capacity  [GW$_{el}$]        54.8474
                              capexCap  [1e6 Euro/a]       4141.16
                              invest    [1e6 Euro]         46620.3
                              operation [GW$_{el}$*h/a]    55026.6
                              opexCap   [1e6 Euro/a]       1398.61
                              opexOp    [1e6 Euro/a]       110.053

In [62]:
i.extend(['CCGT plants (NGas)_stock_2030'])
esM2040.getOptimizationSummary("ConversionModel", outputLevel=2).loc[i]

                                                        EnergyLand
Component                     Property  Unit
CCGT plants (NGas)_stock_2020 TAC       [1e6 Euro/a]       5582.63
                              capacity  [GW$_{el}$]        54.8474
                              capexCap  [1e6 Euro/a]       4141.16
                              invest    [1e6 Euro]         46620.3
                              operation [GW$_{el}$*h/a]      21431
                              opexCap   [1e6 Euro/a]       1398.61
                              opexOp    [1e6 Euro/a]       42.8621

In [63]:
i.extend(['CCGT plants (NGas)_stock_2040'])
esM2050.getOptimizationSummary("ConversionModel", outputLevel=2).loc[i]

Empty DataFrame
Columns: [EnergyLand]
Index: []

In [70]:
i.extend(['Wind_Onshore_stock_2030'])
esM2050.getOptimizationSummary("SourceSinkModel", outputLevel=2).loc['Wind_Onshore']

                          EnergyLand
Property  Unit
TAC       [1e6 Euro/a]       94435.5
capacity  [GW$_{el}$]            620
capexCap  [1e6 Euro/a]       78935.5
invest    [1e6 Euro]          775000
operation [GW$_{el}$*h/a]     230220
opexCap   [1e6 Euro/a]         15500